### model
model_name_or_path: /data/cache_dir/models/zai-org/GLM-4.5-Air
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32  # alpha/rank = 4, standard ratio
lora_dropout: 0.05
lora_target: q_proj,k_proj,v_proj,o_proj

### dataset
dataset: korean_reasoning_train  # Full 176K samples
template: glm4_moe
cutoff_len: 32000  # 99.5% of data is under 20K tokens, 32K is safe
# max_samples: 20  # Not needed - test dataset only has 10
overwrite_cache: true
preprocessing_num_workers: 32  # Tokenization workers (can go higher with 500GB RAM)
dataloader_num_workers: 8  # Data loading workers during training

### output
output_dir: saves/glm45-air/lora/sft
logging_steps: 100  # Log every 100 steps
save_steps: 5000  # ~18 saves per epoch
save_total_limit: 2
plot_loss: true
overwrite_output_dir: true  # Delete old checkpoints, start fresh
save_only_model: false  # Save optimizer states for resume
report_to: wandb  # Disabled for faster testing

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
weight_decay: 0.1
optim: adamw_torch
bf16: true
gradient_checkpointing: true  # 메모리 절약 (필수!)
ddp_timeout: 180000000
# resume_from_checkpoint: saves/glm45-air/lora/sft/checkpoint-3

# ### deepspeed
deepspeed: examples/deepspeed/ds_z3_config.json  

## eval
eval_dataset: korean_reasoning_eval
val_size: 0.0
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 5000  # ~18 evals per epoch